// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg8YUeZIdDVfbNWlvlO6xHX2vab_-KeuA',
    appId: '1:352452654649:web:b00e604e9f72ac9d81bfe8',
    messagingSenderId: '352452654649',
    projectId: 'freshly-e154b',
    authDomain: 'freshly-e154b.firebaseapp.com',
    storageBucket: 'freshly-e154b.firebasestorage.app',
    measurementId: 'G-V3E99HHHDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWseR0M4JPtuFjjHjs4DpfyooWBmpIFzo',
    appId: '1:352452654649:android:2fbaf92063fc737c81bfe8',
    messagingSenderId: '352452654649',
    projectId: 'freshly-e154b',
    storageBucket: 'freshly-e154b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB2s3ovDxVM5vLpZbxvE9aoZKIDc5apNM',
    appId: '1:352452654649:ios:2a992f806295a46c81bfe8',
    messagingSenderId: '352452654649',
    projectId: 'freshly-e154b',
    storageBucket: 'freshly-e154b.firebasestorage.app',
    iosBundleId: 'com.example.freshly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB2s3ovDxVM5vLpZbxvE9aoZKIDc5apNM',
    appId: '1:352452654649:ios:2a992f806295a46c81bfe8',
    messagingSenderId: '352452654649',
    projectId: 'freshly-e154b',
    storageBucket: 'freshly-e154b.firebasestorage.app',
    iosBundleId: 'com.example.freshly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg8YUeZIdDVfbNWlvlO6xHX2vab_-KeuA',
    appId: '1:352452654649:web:41f1fd999920f22081bfe8',
    messagingSenderId: '352452654649',
    projectId: 'freshly-e154b',
    authDomain: 'freshly-e154b.firebaseapp.com',
    storageBucket: 'freshly-e154b.firebasestorage.app',
    measurementId: 'G-KKMKZD1RMC',
  );

}